name: Update version
#on:
#  push:
#    branches:
#      - main

on:
  workflow_run:
    workflows: ['Pre Commit']
    branches: [main]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Update version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{secrets.CI_GITHUB_TOKEN}}
          WITH_V: true
          DEFAULT_BUMP: patch